steps:
# build the docker image: docker build -t gcr.io/$PROJECT_ID/buildapp:v2 .
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/buildapp:v2', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/buildapp:v2']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'cloud-run-deploy', '--image', 'gcr.io/$PROJECT_ID/buildapp:v2', '--region', 'us-central1', '--allow-unauthenticated']
